@startuml
'https://plantuml.com/class-diagram





用户表 <-- 流程表
技术表格 <-- 流程表
流程状态 <-- 流程表
角色树 <- 用户表
功能树<-- 角色树
用户表 <-- 委托表
合同表 <-- 委托表
委托表 <-- 合同表
样品表 <-- 委托表
委托表 <-- 样品表
class 流程表 {
...
int 技术表格id;
int 处理人id;
int 当前状态;
}
class 技术表格{
    ...
    int 技术表格id;
    表格内容
}
class 用户表{
    ...
    user 用户id;
    role[] 角色id;
}
class 角色树{
    ...
    role 角色id;
    auth[] 权限id;
}
class 功能树{
    ...
    auth 权限id;
    menu[] 可访问的功能菜单;
}
class 委托表{
    ...
    int 创建用户id
    date 创建时间
    user[] 受理工作人员
    int 合同id
    int[] 样品id
}
class 合同表{
    ...
    int 合同id
    int 对应委托id
}
class 样品表{
    int 样品id
    int 对应委托id
    type 样品形式
}
enum 流程状态 {
0.委托填写中
1.市场部审核委托中
2.审核未通过，重新填写委托中
3.委托审核通过
4.合同填写中
5.市场部审核合同中
6.审核未通过，重新填写合同中
7.合同审核通过
8.测试部生成测试方案中
...
}

@enduml