@startuml 审核测试报告
title 审核测试报告

actor 测试部工作人员
entity web
database MongoDB
actor 测试部主管
actor user
actor 授权签字人
测试部工作人员 -> web : 提交测试报告
web -> 测试部主管 : 审批测试报告
loop 测试部主管审批不通过
    测试部主管 -> web : 审批不通过
    web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
    测试部工作人员 -> web : 提交测试报告
    web -> 测试部主管 : 审批测试报告
end
测试部主管 -> web : 审批通过
web -> user : 审批测试报告
loop 用户审批不通过
    user -> web : 审批不通过
    web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
    测试部工作人员 -> web : 提交测试报告
    web -> 测试部主管 : 审批测试报告
    loop 测试部主管审批不通过
        测试部主管 -> web : 审批不通过
        web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
        测试部工作人员 -> web : 提交测试报告
        web -> 测试部主管 : 审批测试报告
    end
    测试部主管 -> web : 审批通过
    web -> user : 审批测试报告
end
user -> web : 审批通过
web -> 授权签字人 : 审批测试报告
loop 授权签字人审批不通过
    授权签字人 -> web: 审批不通过
    web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
    测试部工作人员 -> web : 提交测试报告
    web -> 测试部主管 : 审批测试报告
    loop 测试部主管审批不通过
        测试部主管 -> web : 审批不通过
        web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
        测试部工作人员 -> web : 提交测试报告
        web -> 测试部主管 : 审批测试报告
    end
    测试部主管 -> web : 审批通过
    web -> user : 审批测试报告
    loop 用户审批不通过
        user -> web : 审批不通过
        web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
        测试部工作人员 -> web : 提交测试报告
        web -> 测试部主管 : 审批测试报告
        loop 测试部主管审批不通过
            测试部主管 -> web : 审批不通过
            web -> 测试部工作人员 : 审批未通过, 重新修改测试报告
            测试部工作人员 -> web : 提交测试报告
            web -> 测试部主管 : 审批测试报告
        end
        测试部主管 -> web : 审批通过
        web -> user : 审批测试报告
    end
    user -> web : 审批通过
    web -> 授权签字人 : 审批测试报告
end
@enduml