@startuml 用户上传样品
title 上传样品


actor user
entity web
database DB
actor 测试部工作人员
database cloud
测试部工作人员 -> user : 需要新的样品
user --> user : 线下寄样品
user --> cloud : 线上传输样品
user -> web : "上传样品"按钮
web -> user : 进入样品信息上传界面
user -> web : 输入样品信息
user -> web : 提交
web -> DB : 添加样品信息
web -> 测试部工作人员 : 有新的样品来了
测试部工作人员 -> 测试部工作人员 : 取样品, 继续测试


@enduml